#
# Copyright (C) 2020 Xiaomi Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include $(APPDIR)/Make.defs

PROGNAME = watchx
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_WATCHX)

CSRCS += $(wildcard drivers/*.c)
CSRCS += $(wildcard bsp/*.c)
CSRCS += $(wildcard gui/*.c)
CSRCS += $(wildcard gui/fonts/*.c)
CSRCS += $(wildcard gui/images/*.c)
CSRCS += $(wildcard gui/lv_ext/*.c)
CSRCS += $(wildcard gui/page_manager/*.c)
CSRCS += $(wildcard gui/pages/*.c)

MAINSRC = watchx_main.c

include $(APPDIR)/Application.mk
